### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/extract-serac#1]
For i18n, d'ont you think it would be easier to lad https://github.com/c2corg/c2c_ui/blob/master/src/translations/dist/fr.json instead of hard-coding strings ?

**Comment by brunobesson** [comment]
I found it easier to copy the translation rather than create a mapping between the key and the corresponding i18n value (with context and so on), and assumed these translations should not change a lot.

But of course this could be improved :)

**Comment by cbeauchesne** [comment]
Ok !
